#!/bin/bash

alias lessis="less -IS"

alias k=kubectl
complete -F _complete_alias k
#alias kbb="k --namespace=backbase"
#complete -F _complete_alias kbb

#alias helm2=~/tools/helm2.14.3/helm
#complete -F _complete_alias helm2
#source <(helm2 completion bash | sed 's/_helm/_helm2/g')
#complete -F __start_helm2 helm2

# kubernetes env configs
alias setup-bnp="source $SCRIPT_HOME/baas/bb-bnp/setup-bnp.sh"
alias setup-bnp-kubeconfig="source $SCRIPT_HOME/baas/bb-bnp/setup-bnp-kubeconfig.sh"
alias setup-bnp-docker-ecr-comm="source $SCRIPT_HOME/baas/bb-bnp/setup-bnp-docker-ecr-comm.sh"

alias setup-nbb="source $SCRIPT_HOME/kube/bring-nbb/setup-nbb.sh"
alias setup-nbb-proxyconfig="$SCRIPT_HOME/kube/bring-nbb/setup-nbb-proxyconfig.sh"
alias setup-nbb-kubeconfig="$SCRIPT_HOME/kube/bring-nbb/setup-nbb-kubeconfig.sh"

alias setup-minikube="source $SCRIPT_HOME/kube/minikube/setup-minikube.sh"
alias setup-minikube-kubeconfig-copy="$SCRIPT_HOME/kube/minikube/setup-minikube-kubeconfig-copy.sh"
