#!/bin/bash
script_dir="$( dirname "${BASH_SOURCE[0]}" )"
shared_bash_dir=$script_dir/../shared-bash

export PATH=$PATH:/mnt/d/dev/etc/scripts/baas/bb-bnp
export DEV_SRC=/mnt/d/dev/source
export DEV_DOC=/mnt/d/dev/doc
export KUBE_EDITOR=nano

#source $shared_bash_dir/bash_completion
source ~/.bash_completion.d/complete_alias
source $script_dir/aliases
