#!/bin/bash
script_dir="$( dirname "${BASH_SOURCE[0]}" )"
shared_bash_dir=$script_dir/../shared-bash

#export PATH=$PATH:/mnt/d/dev/etc/scripts/baas/bb-bnp
export DEV_SRC=/mnt/c/dev/source
export DEV_DOC=/mnt/c/dev/doc
export DEV_HOME=/mnt/c/home
export SCRIPT_HOME=/mnt/c/dev/etc/scripts
export KUBE_EDITOR=nano

# if there is some error like: "x509: certificate relies on legacy Common Name field"
# maybe this export can help
#export GODEBUG=x509ignoreCN=0

#source $shared_bash_dir/bash_completion
source ~/.bash_completion.d/complete_alias
source $script_dir/aliases

# bash expand env variables with directory paths
shopt -s direxpand
