#!/bin/bash

alias lessis="less -IS"

alias k=kubectl
complete -F __start_kubectl k
#alias kbb="k --namespace=backbase"
#complete -F __start_kubectl kbb

alias git-bash-unicode="chcp 65001"

# kubernetes env configs
alias setup-bnp="source $SCRIPT_HOME/baas/bb-bnp/setup-bnp.sh"
alias setup-bnp-kubeconfig="source $SCRIPT_HOME/baas/bb-bnp/setup-bnp-kubeconfig.sh"
alias setup-bnp-docker-ecr-comm="source $SCRIPT_HOME/baas/bb-bnp/setup-bnp-docker-ecr-comm.sh"

alias setup-nbb="source $SCRIPT_HOME/kube/bring-nbb/setup-nbb.sh"
alias setup-nbb-proxyconfig="$SCRIPT_HOME/kube/bring-nbb/setup-nbb-proxyconfig.sh"
alias setup-nbb-kubeconfig="$SCRIPT_HOME/kube/bring-nbb/setup-nbb-kubeconfig.sh"

# java env configs
JAVA_CANDIDATES_FOLDER="/c/Users/jluzio/.sdkman/candidates/java"
alias java-default="export JAVA_HOME=$JAVA_CANDIDATES_FOLDER/current"
alias java-8="export JAVA_HOME=$JAVA_CANDIDATES_FOLDER/8.0.292.hs-adpt"
alias java-11="export JAVA_HOME=$JAVA_CANDIDATES_FOLDER/11.0.11.hs-adpt"

source $SDKMAN_DIR/candidates/springboot/current/shell-completion/bash/spring
