#!/bin/bash
script_dir="$( dirname "${BASH_SOURCE[0]}" )"
shared_bash_dir=$script_dir/../shared-bash

export PATH=$PATH:/d/dev/etc/scripts/baas/bb-bnp
export DEV_SRC=/d/dev/source
export DEV_DOC=/d/dev/doc
#export KUBE_EDITOR=nano
export KUBE_EDITOR="'`cygpath -u "C:\Program Files\Notepad++\notepad++.exe"`'"

source $shared_bash_dir/bash_completion
source $script_dir/aliases
