#!/bin/bash
script_dir="$( dirname "${BASH_SOURCE[0]}" )"

#export PATH=$PATH
export DEV_SRC=/c/dev/source
export DEV_DOC=/c/dev/doc
export DEV_HOME=/c/home
export SCRIPT_HOME=/c/dev/etc/scripts
#export KUBE_EDITOR=nano
export KUBE_EDITOR="'`cygpath -u "C:\Program Files\Notepad++\notepad++.exe"`'"

source ~/bash-completion/bash_completion
source ~/.bash_completion.d/complete_alias
source $script_dir/aliases

# bash expand env variables with directory paths
shopt -s direxpand
